---
title: "Netflix"
author: "Diana Lin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!--## Netflix-->
Load the packages:
```{r load, message = FALSE, warning = FALSE}
library(tidyverse)
library(lubridate)
library(knitr)
library(DT)
library(here)
library(plotly)
```

Read in the Netflix viewing activity:
```{r di data, message = FALSE}
raw_di <- read_csv(here("data", "raw", "NetflixViewingHistory_Diana.csv"))
raw_bri <- read_csv(here("data", "raw", "NetflixViewingHistory_Brian.csv"))
raw_vic <- read_csv(here("data", "raw", "NetflixViewingHistory_Vicky.csv"))
raw_kev <- read_csv(here("data", "raw", "NetflixViewingHistory_Kevin.csv"))
```

### Diana's Viewing Activity
```{r view di, echo = FALSE}
datatable(raw_di)
```

### Brian's Viewing Activity
```{r view bri, echo = FALSE}
datatable(raw_bri)
```

### Vicky's Viewing Activity
```{r view vic, echo = FALSE}
datatable(raw_vic)
```

### Kevin's Viewing Activity
```{r view kev, echo = FALSE}
datatable(raw_kev)
```

### Data Processing
Label each item with `User`:
```{r mutate}
processed_di <- raw_di %>%
  mutate(User = "Diana")

processed_bri <- raw_bri %>%
  mutate(User = "Brian")

processed_vic <- raw_vic %>%
  mutate(User = "Vicky")

processed_kev <- raw_kev %>%
  mutate(User = "Kevin")
```


Combine the datasets together:
```{r combine}
data <- rbind(processed_di,processed_bri,processed_vic,processed_kev)
```

Count the titles:
```{r count}
processed <- data %>%
  group_by(year(Date), month(Date, label = TRUE), User) %>%
  summarise(count = n()) %>%
  rename(Year = `year(Date)`,
         Month = `month(Date, label = TRUE)`) %>%
  complete(Year, Month, User) %>%
  mutate(count = replace_na(count, 0))
```


### Summary

<!-- Plot a bar graph:-->
```{r bar, echo = FALSE, eval = FALSE}
raw_di %>%
  filter(year(Date) != 2020) %>%
  ggplot(aes(x=month(Date, label = TRUE))) +
  geom_bar() +
  facet_wrap(~ year(Date), ncol =3) +
  labs(title = "Netflix Activity",
       x = "Month",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 90))
```

Plot the data:
```{r point line, out.width='100%'}
history <- processed %>%
  filter(Year != 2020) %>%
  ggplot(aes(x = Month, colour = User, text = paste0("Month: ", Month, "</br></br> Count: ", count))) +
  geom_line(aes(x = Month, y = count, group = User)) +
  geom_point(aes(x = Month, y = count, color = User), shape = 20) +
  facet_wrap(~ Year, ncol = 3) +
  labs(title = "Netflix Viewing History",
       x = "Month",
       y = "Count") +
  theme(text = element_text(size = 12),
        axis.text.x = element_text(angle = 90))

print(history)
```

```{r ggplotly-all, eval = FALSE, include=FALSE}
ggplotly(history, tooltip = c("text"))
```

Plot the 2020 data:
```{r point line current, out.width='100%'}
tt <- data %>%
  filter(year(Date) == 2020) %>%
  group_by(Date, User) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = Date, colour = User, text = paste0("Date: ", month(Date, label = TRUE), " ", day(Date), ", ", year(Date), "</br></br>Count: ",count))) +
  geom_line(aes(x = Date, y = count, group = User)) +
  geom_point(aes(x = Date, y = count, color = User), shape = 20) +
  labs(title = "Netflix Viewing (2020)",
       x = "Date",
       y = "Count") +
  theme(text = element_text(size = 12),
        axis.text.x = element_text(angle = 90))

print(tt)
```

```{r, ggplotly-2020, eval = FALSE, include=FALSE}
ggplotly(tt, tooltip = c("text"))
```

Plot the Quarantine Data (March 14-Present):

```{r quarantine}
q <- data %>%
  filter(Date > date("2020-03-13")) %>%
  group_by(Date, User) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = Date, colour = User, text = paste0("Date: ", month(Date, label = TRUE), " ", day(Date), ", ", year(Date), "</br></br>Count: ",count))) +
  geom_line(aes(x = Date, y = count, group = User)) +
  geom_point(aes(x = Date, y = count, color = User), shape = 20) +
  labs(title = "Netflix Viewing (Quarantine)",
       subtitle = "March 14 to present",
       x = "Date",
       y = "Count") +
  theme(text = element_text(size = 12))
  
print(q)
```

```{r, ggplotly-2020-q, eval = FALSE, include=FALSE}
ggplotly(q, tooltip = c("text"))
```
